spring:
  application:
    version: 1.0.0
  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: false
  main:
    web-application-type: none
    #banner-mode: off

application:
  title: NHN CLOUD CLI TOOL

logging:
  level:
    root: off

skm:
  base-url: https://api-keymanager.alpha-nhncloudservice.com
