spring:
  application:
    version: 1.0.0
  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: false
  main:
    web-application-type: none
    #banner-mode: off

application:
  title: NHN CLOUD CLI TOOL

logging:
  level:
    root: off

skm:
  domains:
    alpha: https://api-keymanager.alpha-nhncloudservice.com
    beta: https://api-keymanager.beta-nhncloudservice.com
    real: https://api-keymanager.nhncloudservice.com
    ngsc: https://api-keymanager.ngsc.go.kr
    ninc: https://api-keymanager.ninc.go.kr
    ncgn: https://ppp-api-keymanager.cloud.toastoven.net
    ngsc-beta: https://api-keymanager.beta-gncloud.go.kr
    gov-alpha: https://api-keymanager.alpha-gov-nhncloudservice.com
    gov-beta: https://api-keymanager.beta-gov-nhncloudservice.com
    gov: https://api-keymanager.gov-nhncloudservice.com
